spring:
  application:
    name: demo3
  data:
    mongodb:
      uri: mongodb://root:12345678@localhost:27017/admin
#        uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:12345678@localhost:27017/admin}

  jpa:
    show-sql: true
  servlet:
    multipart:
      max-request-size: 20MB

logging:
  level:
    root: INFO
